### PR TITLE
Add a windows screenshot and a few small changes

### PR DESCRIPTION
**Pull request by superscratch444tre**

### CODE REVIEW

**Comment by Secret-chest** [comment]
Should I promote Windows?
Anyways, use the Snipping Tool and choose "Window". Then, capture only that window. This is to be consistent with the Linux screenshot.

**Comment by Secret-chest** [comment]
@superscratch444tre

**Comment by superscratch444tre** [comment]
> Should I promote Windows?
> Anyways, use the Snipping Tool and choose "Window". Then, capture only that window. This is to be consistent with the Linux screenshot.

Sorry, i didn't see your comment. Should I change it now? @Secret-chest

**Comment by Secret-chest** [comment]
> > Should I promote Windows?
> > Anyways, use the Snipping Tool and choose "Window". Then, capture only that window. This is to be consistent with the Linux screenshot.
> 
> Sorry, i didn't see your comment. Should I change it now? @Secret-chest

Yes. I merged it anyways, send a new PR.

**Comment by Secret-chest** [comment]
@superscratch444tre Can you update the screenshot? It's getting old.

**Pull request merged**
